#! /bin/sh

SWD=$(readlink -f "$0" | xargs dirname)

for dot in .[a-zA_Z0-9_]*; do 
  if [ -e $HOME/$dot ]; then
	 mv -f $HOME/$dot $HOME/$dot.old
  fi 
  case $dot in
	  . | .. | .git )
	  	continue;;
	  * )
		ln -s $SWD/$dot $HOME/$dot
  esac
done
